services:
  - docker

script:
  ## Build
  - docker build -t udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t udagram-api-user:v1 ./udagram-api-user
  - docker build -t udagram-frontend:v3 ./udagram-frontend
  - docker build -t reverseproxy:v1 ./udagram-reverseproxy
  ## Tag
  - docker tag udagram-api-feed:v1 miatran1109/udagram-api-feed:v1
  - docker tag udagram-api-user:v1 miatran1109/udagram-api-user:v1
  - docker tag udagram-frontend:v3 miatran1109/udagram-frontend:v3
  - docker tag reverseproxy:v1 miatran1109/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push miatran1109/udagram-api-feed:v1
  - docker push miatran1109/udagram-api-user:v1
  - docker push miatran1109/udagram-frontend:v3
  - docker push miatran1109/reverseproxy:v1